apiVersion: v1
kind: Service
metadata:
  name: admin-ui-svc
  labels:
    app: admin-ui
spec:
  type: ClusterIP
  clusterIP: ip
  ports:
  - port: 80
    name: http
    targetPort: 8081
  - port: 443
    name: https
    targetPort: 8081
  selector:
    app: admin-ui